on:
  workflow_dispatch: 

jobs:
  ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install libmagic1 libmagic-dev pkg-config

      - run: |
          which pkg-config
          pkg-config --version

      - run: pkg-config --debug --validate libmagic

      - run: |
          pkg-config --static --libs --cflags libmagic
          pkg-config --libs --cflags libmagic
  macos:
    runs-on: macos-12

    steps:
      - run: |
          brew update
          brew install libmagic pkg-config

      - run: |
          which pkg-config
          pkg-config --version
          brew --version

      - run: pkg-config --debug --validate libmagic

      - run: |
          pkg-config --static --libs --cflags libmagic
          pkg-config --libs --cflags libmagic

  windows:
      runs-on: windows-2022
      env:
        VCPKG_BINARY_SOURCES: clear;x-gha,readwrite

      steps:
        - uses: actions/github-script@v6
          with:
            script: |
              core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
              core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

        - run: |
            vcpkg install update
            vcpkg install libmagic

        - run: |
            vcpkg version

        - run: |
            vcpkg search libmagic
            vcpkg depend-info libmagic
